<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>fileTypes</key>
        <array>
            <string>.saos10</string>
        </array>
        <key>name</key>
        <string>Ciena SAOS10 Minimal</string>
        <key>scopeName</key>
        <string>source.ciena.saos10</string>

        <key>patterns</key>
        <array>
            <!-- Comments -->
            <dict>
                <key>match</key>
                <string>^#.*$</string>
                <key>name</key>
                <string>comment.line.number-sign.saos10</string>
            </dict>

            <!-- Key Commands and Parameters -->
            <dict>
                <key>match</key>
                <string>\b(fd-name|fd|fp|fd-name|classifier-list|push-vid)\b</string>
                <key>name</key>
                <string>entity.name.function.saos10</string>
            </dict>

            <!-- Strings -->
            <dict>
                <key>match</key>
                <string>"[^"]*"</string>
                <key>name</key>
                <string>string.quoted.double.saos10</string>
            </dict>

            <!-- Booleans -->
            <dict>
                <key>match</key>
                <string>\b(true|false|enable|disable|enabled|disabled|on|off)\b</string>
                <key>name</key>
                <string>support.constant.saos10</string>
            </dict>

            <!-- Integers -->
            <dict>
                <key>match</key>
                <string>(?&lt;!\w-)\b\d+\b(?!\-\w)</string>
                <key>name</key>
                <string>constant.numeric.saos10</string>
            </dict>
            <!-- Exit Keyword -->
            <dict>
                <key>match</key>
                <string>^exit\b</string>
                <key>name</key>
                <string>keyword.control.saos10</string>
            </dict>
        </array>
    </dict>
</plist>